### ISSUE TITLE
Consider migrating to the new Input System

### ISSUE THREAD

**Issue by kjy5** [VirtualBrainLab/Pinpoint#116]
- Currently, project is using legacy input system which is sunsetting
- New input system also enables automated UI testing
- Unit testing does not work with "both" enabled

**Comment by kjy5** [comment]
#117

**Comment by dbirman** [comment]
This wouldn't take much work with the current setup, but before tackling this I want to separate the control functionality into its own component (ProbeController) instead of having that in ProbeManager. This would also break what @yonibrowning has developed (again, not hard to fix though). For now I'm putting this on the 1.0 milestone.

**Comment by dbirman** [comment]
For controller support, see new scale controls: https://www.newscaletech.com/wp-content/uploads/MPM-Pathfinder-Xbox-Controller-Diagram.png

**Comment by dbirman** [comment]
- [x] Forward axis
- [ ] Side axis
- [ ] Z/Depth
- [x] PrevProbe/NextProbe
- [ ] Key holding
- [ ] Drag detection

**Comment by dbirman** [comment]
0df2db1539b13869b0569af7bd5106a49f74a11c

Not doing drag detection for now

**Comment by dbirman** [comment]
Closing this issue, and breaking out remaining features into their own issues
