### ISSUE TITLE
Is it possible to support NeuroStar micro-controller for the Electrophysiology Manipulator Link 

### ISSUE THREAD

**Issue by Virginia9733** [VirtualBrainLab/Pinpoint#242]
Hi there, thank you for developing this great tool! 

May I ask is it possible to support the NeuroStar microcontroller for the Electrophysiology Manipulator Link in the near future?

**Comment by dbirman** [comment]
Hey @Virginia9733, when I asked the NeuroStar folks at SfN if they had an API they said they didn't. We can't do much unless we can talk to their controllers from Pinpoint.

I would encourage you to reach out to them and ask them to open-source their controller API, once they do that we can take it from there. Closing this issue for now since there isn't much we can do about it, but if you hear back and they have an API available please reach out to us and let us know!
