### ISSUE TITLE
Enable proxy server read/write for ephys-link

### ISSUE THREAD

**Issue by dbirman** [VirtualBrainLab/Pinpoint#358]
Use UUID to find Ephys Link or use Proxy server to manage communication to Ephys Link

- [ ] On WebGL, swap connection interface with UUID input
- [ ] Connect to proxy server as receiver

**Comment by dbirman** [comment]
Following up on this conversation https://int-brain-lab.slack.com/archives/CU7EP9A2H/p1697709169857369

It looks like using plain Websockets we can do this:

On the WebGL side:
```
        this.socket = new WebSocket("ws://localhost:8765");
```

And on the Python side see https://github.com/int-brain-lab/ephys-atlas-web/blob/main/websock.py for an example

**Comment by kjy5** [comment]
Interesting. So looks like the suggestion here is to abandon socketio and switch to plain websockets? We will have to consider implementing some of the features automatically made present in socketio such as automatic reconnection, but this could be a viable path. Godot will certainly be easier since it has websocket support. I am still a bit hesitant to switch since socketio was designed to fix the issues with websockets, but if it does indeed help us avoid a proxy server then that might be advantageous for users.
